print ("Please enter your name")
sname = input()
print ("Now please enter your address")
saddress = input()
f = open("namesandaddress.txt","a")
f.write(sname + "\n")
f.write(saddress + "\n")
f.close()
